# Generated by Django 4.2.24 on 2025-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='adminid',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.IntegerField(max_length=20),
        ),
    ]
