# Generated by Django 4.2.24 on 2025-09-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_alter_admindetails_adminid_alter_userdetails_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='adminid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
