# Generated by Django 4.2.24 on 2025-10-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_assistancecall_firewater_generalincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancecall',
            name='call_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firewater',
            name='call_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='generalincident',
            name='call_number',
            field=models.CharField(max_length=50),
        ),
    ]
