# Generated by Django 4.2.24 on 2025-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_alter_assistancecall_call_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewater',
            name='approximate_loss',
        ),
        migrations.RemoveField(
            model_name='generalincident',
            name='approximate_loss',
        ),
        migrations.AlterField(
            model_name='firewater',
            name='property_lost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='firewater',
            name='property_saved',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generalincident',
            name='property_lost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generalincident',
            name='property_saved',
            field=models.IntegerField(),
        ),
    ]
